# Generated by Django 5.0.6 on 2024-05-18 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('numberEpisodes', models.IntegerField()),
                ('date', models.DateField()),
                ('rating', models.FloatField()),
                ('img', models.FileField(upload_to='series/media/images/')),
                ('trailerVideo', models.FileField(upload_to='series/media/trailers/')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.FileField(upload_to='series/media/listVideos/images/')),
                ('video', models.FileField(upload_to='series/media/listVideos/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.JSONField(default=list)),
                ('seasons', models.ManyToManyField(to='series.seasons')),
            ],
        ),
        migrations.AddField(
            model_name='seasons',
            name='videos',
            field=models.ManyToManyField(to='series.videos'),
        ),
    ]
