# Generated by Django 5.0.6 on 2024-06-02 18:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('admin', models.BooleanField()),
                ('password', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='users/media/')),
            ],
        ),
    ]
