# Generated by Django 5.0.6 on 2024-05-17 21:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.JSONField(default=list)),
                ('rating', models.FloatField()),
                ('date', models.DateField()),
                ('image', models.URLField()),
                ('trailerVideo', models.URLField()),
                ('video', models.URLField()),
            ],
        ),
    ]
