# Generated by Django 5.0.6 on 2024-05-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.FileField(upload_to='movies/images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailerVideo',
            field=models.FileField(upload_to='movies/trailers/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(upload_to='movies/videos/'),
        ),
    ]
