# Generated by Django 5.0.6 on 2024-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_image_alter_movie_trailervideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.FileField(upload_to='movies/media/images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailerVideo',
            field=models.FileField(upload_to='movies/media/trailers/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(upload_to='movies/media/videos/'),
        ),
    ]
